### PR TITLE
updated to julia 1.0

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by peakbook** [comment]
I am sorry for my slow response, and thank you for the code you've commited.

**Comment by adamnemecek** [comment]
Thanks for merging it. 

I think that your quaternion fourier package (https://github.com/peakbook/QuaternionFourierTransform.jl) is a bit out of date too now. 

I would be eternally grateful if you could take a quick peek, I think that it shouldn't take you more than 30 minutes to update it to julia 1.0. I tried my hand but I'm not super comfortable with neither Julia nor qft so it was quite a lot of struggle.

Thanks for the packages they have been very helpful. Would you know how to extend qft to dual quaternions by the way?

**Comment by peakbook** [comment]
I revised the QFT package. Please check the [example code](https://github.com/peakbook/QuaternionFourierTransform.jl/blob/master/example/ex.jl).

I have no idea how to extend qft to dual quaternions now.

**Comment by adamnemecek** [comment]
Thanks so much! I’ll check it later today.

**Pull request merged**
